### ISSUE TITLE
read start indices

### ISSUE THREAD

**Issue by thirtyeggs** [galaxy001/pirs#1]
Hello,

I change the pirs version from V1.10 to V2.01 and it seems that the format of .info file is changed. In the new version, both of reads in a pair have the same start index. It would be possible to calculate the start index of the second read (read with a larger start index) using insert length, number of insertions in the second read, and the number of deletions in the second read. However, I cannot determine which one is the second one.
Could you tell me how to solve the problem? It would be great if both the reads have their own indices. In simulate_Illumina_reads.cpp ov V1.10, two lines might need to be changed as follows. I hope this would be helpful if you add the feature.

Line 728
read2_pos = pos+insertsize-InputParameter.Read_length-r2_slen+1;
->
read2_pos = pos+insertsize-InputParameter.Read_length+r2_slen+1;

Line 732
read1_pos = pos+insertsize-InputParameter.Read_length-r1_slen+1;
->
read1_pos = pos+insertsize-InputParameter.Read_length+r1_slen+1;

Thanks,
Yun

**Comment by paulinefx** [comment]
Hello,

I have the same issue. Is there a way to fix this problem ? Or it is possible to download the V1.10 of pIRS somewhere ?

Thanks
Pauline

**Comment by thirtyeggs** [comment]
Hi Pauline,

Modifying simulate_Illumina_reads.cpp as above would solve the problem.

Thanks,
Yun
