### ISSUE TITLE
Non-distributable files copyrighted by Illumina in source

### ISSUE THREAD

**Issue by tillea** [galaxy001/pirs#2]
Hi,

I'm writing you on behalf of the Debian Med team which is a group inside Debian that is packaging free software in live sciences and medicine for official Debian.  I intend to package pIRS as a precondition for a benchmarking test for the tool adapterremoval.

When checking the licence of the files in pIRS I stumbled upon the files src/pirs/MaskQvalsByEamss.\* which has a license linking to the [Illumina license agreement](https://shell.cgrb.oregonstate.edu/sites/default/files/Files/Docs/Illumina/casava/Illumina_Genome_Analyzer_Software_License_Agreement.pdf) which to my understanding is pretty much non-distributable. I wonder whether you've got a different license from the authors for these two files and if yes if you could mention this explicitely somewhere inside its source code.

Kind regards

```
     Andreas.
```

**Comment by galaxy001** [comment]
Sorry, I have not check the license issue. I was thinking quote its original header part is best to track the source and the author. In fact, the function in these 2 files are easy to understand and rewrite.

Before version 2.0, the two files were from:

```
./CASAVA_v1.8.2/src/c++/lib/demultiplex/MaskQvalsByEamss.cpp
./CASAVA_v1.8.2/src/c++/include/demultiplex/MaskQvalsByEamss.hh
```

According to [Illumina official site](http://support.illumina.com/sequencing/sequencing_software/casava.html), CASAVA has been discontinued and replaced by [bcl2fastq](http://support.illumina.com/sequencing/sequencing_software/bcl2fastq-conversion-software.html). However, I just checked its source and I cannot grep "Eamss" from the files.

We have rewrite its code to get rid of `BOOST` and use `C arrays` as data structure in [2014](https://github.com/galaxy001/pirs/commit/ee1a77869f28556240f86a9e98d8b07ac15cd674#diff-338d696fea6295f786fd01ea1fc1cca6). So, I think we can remove its old license now.

So, it is [done](https://github.com/galaxy001/pirs/commit/6f7be09775152855cba340522b24e90aca0f91da).

**Comment by tillea** [comment]
Hi,

On Sat, Aug 13, 2016 at 09:46:09PM -0700, galaxy001 wrote:

> I am not sure whether a discontinued program still have copyright. If it has, I will rewrite those 2 files.

A file doese not loose its copyright only because its not used any more
by its original author.  If you are using it you need to respect its
copyright and as I said without explicit change of the copyright by its
copyright holder you are not even allowed to distribute the files on
your site.

If its easy to rewrite (or possibly find some other existing code with
the same functionality) I would recommend to do so since possibly it
takes longer to try discussing with Illumina about copyright.

Kind regards and thanks for considering this issue

```
  Andreas.
```

## 

http://fam-tille.de

**Comment by galaxy001** [comment]
Please check edited reply on web.

> We have rewrite its code to get rid of `BOOST` and use `C arrays` as data structure in [2014](https://github.com/galaxy001/pirs/commit/ee1a77869f28556240f86a9e98d8b07ac15cd674#diff-338d696fea6295f786fd01ea1fc1cca6). So, I think we can remove its old license now.
> 
> So, it is [done](https://github.com/galaxy001/pirs/commit/6f7be09775152855cba340522b24e90aca0f91da).

Well, the rewrite is not done by me, thus I forgot it.

**Comment by tillea** [comment]
Hi,

On Sat, Aug 13, 2016 at 11:40:24PM -0700, galaxy001 wrote:

> Please check edited reply on web.
> 
> > We have rewrite its code to get rid of `BOOST` and use `C arrays` as data structure in [2014](https://github.com/galaxy001/pirs/commit/ee1a77869f28556240f86a9e98d8b07ac15cd674#diff-338d696fea6295f786fd01ea1fc1cca6). So, I think we can remove its old license now.
> > 
> > So, it is [done](https://github.com/galaxy001/pirs/commit/6f7be09775152855cba340522b24e90aca0f91da).
> 
> Well, the rewrite is not done by me, thus I forgot it.

This commit only rewrites the copyright part.  I tried to find a file

   CASAVA_v1.8.2/src/c++/lib/demultiplex/MaskQvalsByEamss.cpp

but failed.  So it is not clear what the license of the file that should
be copyright of Come Raczy might be.

Kind regards

```
    Andreas.
```

## 

http://fam-tille.de

**Comment by galaxy001** [comment]
The original file is committed on [Mar 31, 2012](https://github.com/galaxy001/pirs/commit/3f0a3d8bf0492da1c52f91a4a9aa894bc09561d0).

You can check its file history.

**Comment by tillea** [comment]
On Mon, Aug 15, 2016 at 04:42:31AM -0700, galaxy001 wrote:

> The original file is committed on [Mar 31, 2012](https://github.com/galaxy001/pirs/commit/3f0a3d8bf0492da1c52f91a4a9aa894bc09561d0).
> 
> You can check its file history.

Yes, sure - but this original file has the non-distributable licensing
statement which was the reason for me to open this issue.  The latest
commit was simply removing the statement.

Am I missing something?

Kind regards

```
    Andreas.
```

## 

http://fam-tille.de

**Comment by galaxy001** [comment]
> We have rewrite its code to get rid of `BOOST` and use `C arrays` as data structure in [2014](https://github.com/galaxy001/pirs/commit/ee1a77869f28556240f86a9e98d8b07ac15cd674#diff-338d696fea6295f786fd01ea1fc1cca6). So, I think we can remove its old license now.

Would you just read the commit above ?

I thought you were looking for original file to do `diff` by yourself instead of by `git`.

Why cannot you just check the file history ?

**Comment by tillea** [comment]
On Mon, Aug 15, 2016 at 06:54:17PM -0700, galaxy001 wrote:

> > We have rewrite its code to get rid of `BOOST` and use `C arrays` as data structure in [2014](https://github.com/galaxy001/pirs/commit/ee1a77869f28556240f86a9e98d8b07ac15cd674#diff-338d696fea6295f786fd01ea1fc1cca6). So, I think we can remove its old license now.
> 
> Would you just read the commit above ?

I did.  As far as I can see it is doing the changes regarding boost and
C arrays and lots of reformatting.

> I thought you were looking for original file to do `diff` by yourself instead of by `git`.
> 
> Why cannot you just check the file history ?

Well, the thing is: If I upload some software to the Debian mirror the
first time some very picky people (our so called ftpmasters) will check
copyright and license of every single file.  They do not dive into any
version control system but will inspect the files as uploaded.  So if
there is a reference which sounds suspicious they will reject the whole
software.  The header of the file says it is based on some code which is
not publicly avialable nor does it have a free license.

Kind regards

```
   Andreas.
```

## 

http://fam-tille.de

**Comment by galaxy001** [comment]
```
 ** This file is based on the Consensus Assessment of Sequence And VAriation
 ** (CASAVA) software package.
 **
 ** \file ./CASAVA_v1.8.2/src/c++/lib/demultiplex/MaskQvalsByEamss.cpp
 **
 ** \brief Masks quality values of a read, using the EAMSS.
 **
 ** \author Come Raczy
 **
 ** \modifed_by Eric Biggers
```

I think this description is OK, as it does not contain  other license information.

The way to do EAMSS is a simple calculation, Illumina implies it with boost and other C++ staffs,  Eric Biggers re-imply it with C staffs. Since the math core must be the same, we can think we have rewritten it.

I have searched "illumina" within on github, and find no other license info. The [new release (v.2.02)](https://github.com/galaxy001/pirs/releases/tag/v2.0.2) is the current status.

---

> The header of the file says it is based on some code which is
> not publicly avialable nor does it have a free license.

er. Sorry, I did not notice this.

Can I change it to "Rewrite accroding to ./CASAVA_v1.8.2/src/c++/lib/demultiplex/MaskQvalsByEamss.cpp" ?

Do you have other opinions to say that we use the same math method of Illumina to do `EAMSS` in the correct way ?

**Comment by galaxy001** [comment]
I assume you did not check the web page of my edited reply.

I read about your concern on referring a non-publicly available  file. I would like to change the header if you can help me to phrase some words to express that: the code is based on the official source code which is freely available until December 31, 2015 and discontinued, and we have totally rewrite its code.

It will be better for us to discuss here and in the end, make one final commit of code on this issue.

**Comment by galaxy001** [comment]
Well, I hope someone familiar with laws can help to re-phrase the current statement of "Rewrite according to CASAVA_v1.8.2".

If the current rewritten version of `MaskQvalsByEamss.cpp` is not enough, please show me the lawful reference and I will try to overcome it.

Since no reply from @tillea for quite a long time, closed.
