### ISSUE TITLE
make error:collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by MIAOKUI** [galaxy001/pirs#3]
Hi 
I try make the source code and I got the error follows:cd ./src/pirs && make -f gccMakefile
make[1]: Entering directory `/gpfs/software/pipeline/softwares/pIRS/pirs-2.0.2/src/pirs'
g++ -Wfloat-equal -Wall -pipe -mtune=generic -msse2 -fopenmp -DSFMT_MEXP=19937 -DHAVE_CONFIG_H -DPKGDATADIR='"/usr/local/share/pirs"' -I. -I.. -ISFMT-src-1.4 -static -march=native -march=native -O2 -o pirs IndelProfile.cpp util.cpp pirs_simulate.cpp InputStream.cpp mt19937-64.cpp OutputStream.cpp GCBiasProfile.cpp BaseCallingProfile.cpp Profile.cpp MaskQvalsByEamss.cpp pirs_diploid.cpp main.cpp SFMT-src-1.4/SFMT.c -Wl,-O1 -Wl,--sort-common -Wl,--enable-new-dtags -Wl,--hash-style=both -lz -lpthread
/usr/bin/ld: cannot find -lz
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libpthread.a(libpthread.o): In function `sem_open':
(.text+0x682b): warning: the use of `mktemp' is dangerous, better use `mkstemp'
collect2: error: ld returned 1 exit status
make[1]: *** [pirs] Error 1
make[1]: Leaving directory `/gpfs/software/pipeline/softwares/pIRS/pirs-2.0.2/src/pirs'
make: *** [simulator] Error 2

Our cluster is based on centos 7.2 , any suggestions about this ?

**Comment by galaxy001** [comment]
`cannot find -lz`, so install zlib-devel or sth. like this.
