### ISSUE TITLE
Expected FASTA tag line in reference sequence "path/Profiles/GC-depth_Profiles/humNew.gcdep_150.dat"

### ISSUE THREAD

**Issue by VenithaB** [galaxy001/pirs#8]
I got the following fatal error:
Expected FASTA tag line in reference sequence "/home/group_AM/Venitha/installations/pirs-master/Profiles/GC-depth_Profiles/humNew.gcdep_150.dat"

Information from the command line:

[pIRS] Program:        pirs (Profile-based Illumina pair-end Reads Simulator)
[pIRS] Version:        2.0.0
[pIRS] Author:         Jianying Yuan (BGI-Shenzhen)
[pIRS] Contact:        yuanjianying@genomics.org.cn
[pIRS] Compile Date:   Mar 10 2019 time: 20:16:23
[pIRS] Current time:   Mon Mar 11 14:25:22 2019
[pIRS] Command line:   pirs simulate Aedes-aegypti-LVP_AGWG_CHROMOSOMES_AaegL5.fa -l 100 -x 25 -o Aedes_AaegL5 -t 6 -B /home/group_AM/Venitha/installations/pirs-master/Profiles/Base-Calling_Profiles/humNew.PE100.matrix.gz -I /home/group_AM/Venitha/installations/pirs-master/Profiles/InDel_Profiles/phixv2.InDel.matrix -G /home/group_AM/Venitha/installations/pirs-master/Profiles/GC-depth_Profiles/humNew.gcdep_100.dat /home/group_AM/Venitha/installations/pirs-master/Profiles/GC-depth_Profiles/humNew.gcdep_150.dat /home/group_AM/Venitha/installations/pirs-master/Profiles/GC-depth_Profiles/humNew.gcdep_200.dat
[pIRS] 
[pIRS] Loading base-calling profile /home/group_AM/Venitha/installations/pirs-master/Profiles/Base-Calling_Profiles/humNew.PE100.matrix.gz
[pIRS] Loaded base-calling profile header:
[pIRS]    num_ref_bases      = 4
[pIRS]    num_cycles         = 200
[pIRS]    num_seq_bases      = 4
[pIRS]    num_quality_scores = 41
[pIRS] Loading DistMatrix of base-calling profile
[pIRS] Loading QTransMatrix of base-calling profile
[pIRS] Done loading Base-Calling profile.
[pIRS] Loading InDel error profile /home/group_AM/Venitha/installations/pirs-master/Profiles/InDel_Profiles/phixv2.InDel.matrix
[pIRS] Indel error profile statistics:
[pIRS]     max_indel_len = 3
[pIRS]     num_cycles    = 200
[pIRS]     read_1_count  = 147091454
[pIRS]     read_2_count  = 145785569
[pIRS]     Insertion-bp rate of 100-bp read 1 = 0.000478%
[pIRS]     Deletion-bp rate of 100-bp read 1  = 0.001118%
[pIRS]     Insertion-bp rate of 100-bp read 2 = 0.000837%
[pIRS]     Deletion-bp rate of 100-bp read 2  = 0.001551%
[pIRS] Done loading InDel error profile.
[pIRS] Loading GC bias profile /home/group_AM/Venitha/installations/pirs-master/Profiles/GC-depth_Profiles/humNew.gcdep_100.dat
[pIRS] GC bias profile (GC content, relative abundance), showing every 10%
[pIRS]     0%	0.0100963
[pIRS]     10%	0.223365
[pIRS]     20%	0.91113
[pIRS]     30%	0.977994
[pIRS]     40%	0.944499
[pIRS]     50%	0.790401
[pIRS]     60%	0.633665
[pIRS]     70%	0.313147
[pIRS]     80%	0.101214
[pIRS]     90%	0.00646478
[pIRS]     100%	0.00465393
[pIRS] Done loading GC bias profile.
[pIRS] 
[pIRS] Beginning simulation with the following parameters:
[pIRS] 
[pIRS] Read length:                      100
[pIRS] Insert length mean:               180
[pIRS] Insert length standard deviation: 18
[pIRS] Coverage:                         25
[pIRS] Diploid:                          no
[pIRS] Cyclized (jumping library):       no
[pIRS] Simulate substitution errors:     yes
[pIRS] Substitution error rate:          default of base-calling profile
[pIRS] Base-calling profile:             /home/group_AM/Venitha/installations/pirs-master/Profiles/Base-Calling_Profiles/humNew.PE100.matrix.gz
[pIRS] Substitution error algorithm:     quality transition mode algorithm
[pIRS] Simulate InDel errors:            yes
[pIRS] InDel error profile:              /home/group_AM/Venitha/installations/pirs-master/Profiles/InDel_Profiles/phixv2.InDel.matrix
[pIRS] Simulate GC content bias:         yes
[pIRS] GC bias profile:                  /home/group_AM/Venitha/installations/pirs-master/Profiles/GC-depth_Profiles/humNew.gcdep_100.dat
[pIRS] Output type:                      text
[pIRS] Output directory:                 Aedes_AaegL5
[pIRS] Indiv name:                       
[pIRS] Simulate quality values:          yes
[pIRS] ASCII shift of quality value      33
[pIRS] Mode of mask quality:             None
[pIRS] Random seed:                      9060743124914
[pIRS] Number of simulator threads:      6
[pIRS] 
.
.
. (Reads are generated for all the chromosomes)
.
.
**[pIRS] FATAL ERROR:
Expected FASTA tag line in reference sequence "/home/group_AM/Venitha/installations/pirs-master/Profiles/GC-depth_Profiles/humNew.gcdep_150.dat"**

**Comment by VenithaB** [comment]
Also,  I installed pirs by cloning from git.

**Comment by galaxy001** [comment]
I tried the git version of `git clone https://github.com/galaxy001/pirs.git`, and `make test`/`pirs/src/pirs/test/pirs.sh` works.

The C++ programmer has left. I may try to learn C++ later.

**Comment by VenithaB** [comment]
No, I don't have a problem installing the program. I encountered the error I have mentioned above quite at the end of the simulation. Can you let me know how to rectify the error?

**Comment by galaxy001** [comment]
The "REFERENCE.FASTA" should not contain empty lines.

<https://github.com/galaxy001/pirs/blob/bee9b594f4d0e10580aae77ec411cecec4a77219/src/pirs/util.cpp#L144>
